name: Windows Server - RustDesk Connection

on:
  workflow_dispatch:

jobs:
  build:
    name: Starting Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Installing Essentials & Running Services
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/4p7jhajtwqy2ezyap2y24/Downloads.bat?rlkey=2jggcl13ml1rxcw1orc5af1r0&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat